"""Regular and nested spectral random-field generators."""

from __future__ import annotations

from functools import partial
import math

import jax
import jax.numpy as jnp
import jax.random as rnd

from .grid_utils import GridWorkspace, NestedGridWorkspace


def _normal_samples(key, size: int, nsub: int):
    """Generate a deterministic flat stream of standard-normal samples.

    Parameters
    ----------
    key : jax.Array
        JAX PRNG key identifying the random stream.
    size : int
        Number of samples to return.
    nsub : int
        Maximum number of samples generated by each folded-in substream.
        Values larger than ``size`` are capped to avoid oversized temporary
        allocations.

    Returns
    -------
    jax.Array
        One-dimensional array of length ``size``.

    Notes
    -----
    Folding a block index into ``key`` makes the result deterministic and
    independent of which device evaluates a refinement level.
    """
    block_size = min(size, nsub)
    nblocks = math.ceil(size / block_size)
    keys = jax.vmap(rnd.fold_in, in_axes=(None, 0))(
        key, jnp.arange(nblocks, dtype=jnp.uint32)
    )
    blocks = jax.vmap(
        lambda block_key: rnd.normal(block_key, shape=(block_size,))
    )(keys)
    return blocks.reshape(-1)[:size]


def _band_limited_realization(
    key,
    dk,
    d3k,
    spectrum,
    k_low,
    k_high,
    *,
    rshape,
    cshape,
    nsub,
):
    """Generate one unnormalised rectangular, band-limited realization.

    Parameters
    ----------
    key : jax.Array
        PRNG key for this realization and refinement level.
    dk : array-like, shape (3,)
        Fourier sample spacing along each axis, in inverse length units.
    d3k : float or jax.Array
        Fourier-cell volume, equal to ``prod(dk)``.
    spectrum : jax.Array, shape (2, M)
        Tabulated wavenumbers and their target power ``[k, P(k)]``.
    k_low, k_high : float or jax.Array
        Radial Fourier-band bounds. The lower bound is open when positive and
        the upper bound is closed: ``k_low < |k| <= k_high``.
    rshape : tuple of int
        Real-space array shape ``(Nx, Ny, Nz)``.
    cshape : tuple of int
        Corresponding rFFT shape ``(Nx, Ny, Nz // 2 + 1)``.
    nsub : int
        Maximum random substream block size.

    Returns
    -------
    jax.Array
        Unnormalised real field with shape ``rshape``.

    Notes
    -----
    Noise is generated in real space before the rFFT so that the Hermitian
    constraints on the half-complex boundary planes are satisfied exactly.
    """
    # Starting from real-space noise guarantees the Hermitian constraints on
    # the rFFT boundary planes. Arbitrary half-complex noise does not.
    noise = _normal_samples(key, math.prod(rshape), nsub).reshape(rshape)
    delta_k = jnp.fft.rfftn(noise)
    delta_k = delta_k.at[0, 0, 0].set(0.0 + 0.0j)

    kx = jnp.fft.fftfreq(rshape[0]) * dk[0] * rshape[0]
    ky = jnp.fft.fftfreq(rshape[1]) * dk[1] * rshape[1]
    kz = jnp.fft.rfftfreq(rshape[2]) * dk[2] * rshape[2]
    kxa, kya, kza = jnp.meshgrid(kx, ky, kz, indexing="ij")
    kmag = jnp.sqrt(kxa**2 + kya**2 + kza**2)

    white_spectrum = (2.0 * jnp.pi) ** 3 / (math.prod(rshape) * d3k)
    transfer_1d = jnp.sqrt(jnp.maximum(spectrum[1], 0.0) / white_spectrum)
    transfer = jnp.interp(
        kmag.ravel(), spectrum[0], transfer_1d, left=0.0, right=0.0
    ).reshape(cshape)
    lower_mask = jnp.where(k_low <= 0.0, kmag >= 0.0, kmag > k_low)
    band_mask = lower_mask & (kmag <= k_high)
    delta_k = delta_k * transfer * band_mask
    return jnp.fft.irfftn(delta_k, s=rshape)


class Box:
    """Generate one regular-grid 3-D random field from a power spectrum.

    ``Box`` retains the original single-grid behavior: the generated field is
    normalized to unit standard deviation and then multiplied by the optional
    height-dependent ``zscaling`` profile.
    """

    def __init__(
        self,
        grid_wsp: GridWorkspace | None = None,
        field_name: str = "specific humidity",
        field_unit: str = "g kg^-1",
        spectrum: dict | None = None,
        zscaling: dict | None = None,
        seed: int = 123456789,
        nsub: int = 1024**3,
        N=(128, 128, 128),
        Lbox=(10000.0, 10000.0, 10000.0),
        cell_size=None,
        site_altitude: float = 0.0,
        origin=None,
    ) -> None:
        """Initialize a single-grid random-field generator.

        Parameters
        ----------
        grid_wsp : GridWorkspace, optional
            Existing geometry. When supplied, all geometry arguments below
            are ignored.
        field_name, field_unit : str
            Descriptive metadata for downstream atmospheric calculations.
        spectrum : dict
            Mapping with one-dimensional ``"k"`` and ``"pofk"`` arrays.
        zscaling : dict, optional
            Mapping with altitude ``"h"`` and multiplicative amplitude
            ``"f"`` arrays.
        seed : int
            Base random seed.
        nsub : int
            Maximum random substream block size.
        N : int or sequence of three int
            Number of grid cells along each dimension.
        Lbox : float or sequence of three float
            Physical box dimensions. Ignored when ``cell_size`` is supplied.
        cell_size : float or sequence of three float, optional
            Physical cell dimensions. Takes precedence over ``Lbox``.
        site_altitude : float
            Telescope-site altitude used as the default z origin.
        origin : sequence of three float, optional
            Absolute lower corner of the grid.
        """
        if grid_wsp is None:
            grid_wsp = GridWorkspace(
                N=N,
                Lbox=Lbox,
                cell_size=cell_size,
                site_altitude=site_altitude,
                origin=origin,
            )
        if not isinstance(grid_wsp, GridWorkspace):
            raise TypeError("grid_wsp must be a GridWorkspace.")
        if spectrum is None:
            raise ValueError("spectrum is required.")
        if int(nsub) <= 0:
            raise ValueError("nsub must be positive.")

        self.grid_wsp = grid_wsp
        self.field_name = field_name
        self.field_unit = field_unit
        self.spectrum = jnp.asarray([spectrum["k"], spectrum["pofk"]])
        self.zscaling = zscaling
        self.seed = int(seed)
        self.nsub = int(nsub)

    def _key(self, time_step=0):
        """Return the deterministic PRNG key for one simulation time step."""
        return rnd.fold_in(rnd.PRNGKey(self.seed), int(time_step))

    def _random_delta_k(self, time_step=0):
        """Return raw half-complex noise for compatibility with older callers.

        This helper is not used by the realization kernel, which starts from
        real noise to enforce Hermitian symmetry.
        """
        size = math.prod(self.grid_wsp.cshape)
        real_key, imag_key = rnd.split(self._key(time_step))
        values = _normal_samples(real_key, size, self.nsub) + 1j * _normal_samples(
            imag_key, size, self.nsub
        )
        values = values.reshape(self.grid_wsp.cshape)
        return values.at[0, 0, 0].set(0.0 + 0.0j)

    def _rescale_field(self, field):
        """Apply the configured height-dependent amplitude profile."""
        if self.zscaling is None:
            return field
        scaling = self.grid_wsp.interp2grid(
            self.zscaling["h"], self.zscaling["f"]
        )
        return field * scaling

    def generate_field_fluctuations(self, time_step=0):
        """Generate, normalize, and store one field realization.

        Parameters
        ----------
        time_step : int
            Integer folded into the base seed. Reusing the same seed and time
            step reproduces the same realization.

        Returns
        -------
        jax.Array
            Generated field with shape ``grid_wsp.rshape``. The same array is
            stored in :attr:`field`.
        """
        generate = jax.jit(
            partial(
                _band_limited_realization,
                rshape=self.grid_wsp.rshape,
                cshape=self.grid_wsp.cshape,
                nsub=self.nsub,
            )
        )
        raw = generate(
            self._key(time_step),
            self.grid_wsp.dk,
            self.grid_wsp.d3k,
            self.spectrum,
            0.0,
            jnp.linalg.norm(self.grid_wsp.nyquist_k),
        )
        standard_deviation = jnp.std(raw)
        self.field = self._rescale_field(
            jnp.where(standard_deviation > 0.0, raw / standard_deviation, raw)
        )
        return self.field


class NestedBox:
    """Generate independent missing-scale fields on nested rectangular grids.

    Level zero contains the coarse Fourier band. Every subsequent level stores
    only modes above the preceding level's isotropic Nyquist cutoff. Levels
    are never prolonged or combined into a uniform fine grid. On multi-device
    systems, level arrays remain resident on their generation devices until a
    reduced line-of-sight result is combined by :class:`Observer`.
    """

    def __init__(
        self,
        N=(128, 128, 128),
        nlevels: int | None = None,
        Lbox=(10000.0, 10000.0, 10000.0),
        cell_size=None,
        refinement_factor=2,
        grid_wsp: NestedGridWorkspace | None = None,
        telescope_position=None,
        site_altitude: float = 0.0,
        field_name: str = "specific humidity",
        field_unit: str = "g kg^-1",
        spectrum: dict | None = None,
        zscaling: dict | None = None,
        seed: int = 123456789,
        nsub: int = 1024**3,
    ) -> None:
        """Initialize a nested random-field generator.

        Parameters
        ----------
        N : int or sequence of three int
            Cell counts shared by all levels. The three dimensions may differ.
        nlevels : int, optional
            Total number of boxes, including the coarse level.
        Lbox : sequence of three float
            Coarse physical dimensions. Used only when ``cell_size`` is absent.
        cell_size : sequence, optional
            Per-level cell sizes. Shape ``(nlevels,)`` denotes isotropic cells;
            shape ``(nlevels, 3)`` permits anisotropic cells. This argument
            takes precedence over both ``Lbox`` and ``refinement_factor``.
        refinement_factor : float or sequence of three float
            Per-level reduction in box length when deriving levels from
            ``Lbox``.
        grid_wsp : NestedGridWorkspace, optional
            Existing hierarchy. When supplied, geometry arguments are ignored.
        telescope_position : sequence of three float, optional
            Telescope position. Children are centered on it in x/y and remain
            anchored at ``site_altitude`` in z.
        site_altitude : float
            Absolute z coordinate of every level's lower face.
        field_name, field_unit : str
            Descriptive field metadata.
        spectrum : dict
            Mapping with one-dimensional ``"k"`` and ``"pofk"`` arrays.
        zscaling : dict, optional
            Altitude-dependent amplitude mapping with ``"h"`` and ``"f"``.
        seed : int
            Base random seed.
        nsub : int
            Maximum random substream block size.
        Notes
        -----
        After generation, :attr:`increments` contains the independent bands.
        :attr:`fields` is a compatibility alias for the same tuple, while the
        singular :attr:`field` remains ``None`` because no cumulative field is
        constructed.
        """
        if grid_wsp is None:
            grid_wsp = NestedGridWorkspace(
                N=N,
                nlevels=nlevels,
                Lbox=Lbox,
                cell_size=cell_size,
                refinement_factor=refinement_factor,
                telescope_position=telescope_position,
                site_altitude=site_altitude,
            )
        if not isinstance(grid_wsp, NestedGridWorkspace):
            raise TypeError("grid_wsp must be a NestedGridWorkspace.")
        if spectrum is None:
            raise ValueError("spectrum is required.")
        if int(nsub) <= 0:
            raise ValueError("nsub must be positive.")

        self.grid_wsp = grid_wsp
        self.field_name = field_name
        self.field_unit = field_unit
        self.spectrum = jnp.asarray([spectrum["k"], spectrum["pofk"]])
        self.zscaling = zscaling
        self.seed = int(seed)
        self.nsub = int(nsub)
        self.increments = ()
        self.fields = ()
        self.field = None

    def _level_keys(self, time_step):
        """Derive one reproducible PRNG key per refinement level."""
        time_key = rnd.fold_in(rnd.PRNGKey(self.seed), int(time_step))
        return jax.vmap(rnd.fold_in, in_axes=(None, 0))(
            time_key, jnp.arange(self.grid_wsp.nlevels, dtype=jnp.uint32)
        )

    def _generate_increments(self, time_step):
        """Generate unnormalised missing-scale fields on available devices.

        A single device evaluates levels sequentially with one compiled
        kernel. Multiple devices evaluate batches with ``jax.pmap``. Returned
        arrays retain the device placement of their corresponding pmap shard.
        """
        levels = self.grid_wsp.levels
        keys = self._level_keys(time_step)

        def generate_one(key, dk, d3k, limits):
            """Evaluate the realization kernel for one level's geometry."""
            return _band_limited_realization(
                key,
                dk,
                d3k,
                self.spectrum,
                limits[0],
                limits[1],
                rshape=levels[0].rshape,
                cshape=levels[0].cshape,
                nsub=self.nsub,
            )

        dks = jnp.stack([level.dk for level in levels])
        d3ks = jnp.stack([level.d3k for level in levels])
        limits = jnp.asarray(self.grid_wsp.band_limits)
        device_count = jax.local_device_count()

        if device_count == 1:
            compiled = jax.jit(generate_one)
            return tuple(
                compiled(keys[i], dks[i], d3ks[i], limits[i])
                for i in range(self.grid_wsp.nlevels)
            )

        increments = []
        for start in range(0, self.grid_wsp.nlevels, device_count):
            stop = min(start + device_count, self.grid_wsp.nlevels)
            devices = jax.local_devices()[: stop - start]
            parallel_generate = jax.pmap(generate_one, devices=devices)
            batch = parallel_generate(
                keys[start:stop], dks[start:stop], d3ks[start:stop], limits[start:stop]
            )
            increments.extend(
                jnp.squeeze(shard.data, axis=0) for shard in batch.addressable_shards
            )
        return tuple(increments)

    def _scaling_for_level(self, level):
        """Return the vertical amplitude grid for one refinement level."""
        if self.zscaling is None:
            return 1.0
        return level.interp2grid(self.zscaling["h"], self.zscaling["f"])

    def generate_field_fluctuations(self, time_step=0):
        """Generate and store all independent refinement-band fields.

        The common normalization is ``sqrt(sum(var(level)))``. Consequently,
        the variances of the independent bands sum to one before ``zscaling``
        is applied, without changing their relative spectral power.

        Parameters
        ----------
        time_step : int
            Integer folded into the base seed and then into every level key.

        Returns
        -------
        tuple of jax.Array
            One missing-scale field per refinement level. Arrays have the same
            cell shape but different physical geometry and may reside on
            different devices.
        """
        raw_increments = self._generate_increments(time_step)
        # Independent bands remain independent arrays. Their variances add, so
        # one common normalization preserves the relative power across levels.
        total_variance = sum(
            float(jax.device_get(jnp.var(increment)))
            for increment in raw_increments
        )
        normalization = math.sqrt(total_variance) if total_variance > 0.0 else 1.0

        increments = []
        for increment, level in zip(raw_increments, self.grid_wsp.levels):
            device = next(iter(increment.devices()))
            scaling = jax.device_put(self._scaling_for_level(level), device)
            increments.append(increment / normalization * scaling)

        self._raw_increments = raw_increments
        self.increments = tuple(increments)
        # ``fields`` is a compatibility alias; these are missing-scale fields,
        # not cumulative parent fields.
        self.fields = self.increments
        self.field = None
        return self.fields
